name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lms-backend
  DOCKER_FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/lms-frontend
  REACT_APP_API_URL: http://${{ secrets.SERVER_IP }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-flask
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          tags: |
            ${{ env.DOCKER_BACKEND_IMAGE }}:2.0.0
            ${{ env.DOCKER_BACKEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_BACKEND_IMAGE }}:2.0.0
          cache-to: type=inline

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-react
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          build-args: |
            REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
          tags: |
            ${{ env.DOCKER_FRONTEND_IMAGE }}:2.0.0
            ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_FRONTEND_IMAGE }}:2.0.0
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose file
        run: |
          scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/docker-compose.yml

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
            echo "Stopping existing containers..."
            docker-compose down
            echo "Removing old images..."
            docker system prune -af
            echo "Pulling new images..."
            docker-compose pull
            echo "Starting new containers..."
            docker-compose up -d --force-recreate
            echo "Deployment complete!"
          '
